import { StyleSheet} from 'react-native';

export const Colors = {
  primary: '#8BBDD1',
  accent: '#F07167',
  gold: '#E9B464',
  white: '#FFFFFF',
  lightGray: '#F5F5F5',
  darkGray: '#666666',
  textDark: '#1A1A1A',
  borderColor: '#E8E8E8',
};
const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F4F7FB',
  },
  screen: {
    flex: 1,
    backgroundColor: '#F4F7FB',
  },
  header: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(26,26,26,0.04)',
  },
  headerTitle: {
    color: Colors.textDark,
    fontSize: 28,
    fontWeight: '900',
  },
  content: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 12,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 4,
  },
  statCard: {
    flex: 1,
    backgroundColor: Colors.white,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: 'rgba(26,26,26,0.04)',
    alignItems: 'center',
    gap: 5,
    shadowColor: '#000',
    shadowOpacity: 0.02,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  statValue: {
    color: Colors.textDark,
    fontSize: 20,
    fontWeight: '800',
  },
  statLabel: {
    color: Colors.darkGray,
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  sectionCard: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 14,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: 'rgba(26,26,26,0.04)',
    shadowColor: '#000',
    shadowOpacity: 0.02,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
    gap: 12,
  },
  sectionHeader: {
    gap: 8,
  },
  sectionTitle: {
    color: Colors.textDark,
    fontSize: 17,
    fontWeight: '800',
  },
  feedList: {
    gap: 8,
  },
  feedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(26,26,26,0.04)',
    backgroundColor: '#FAFBFD',
  },
  feedRowPressed: {
    opacity: 0.9,
  },
  resultBadge: {
    minWidth: 50,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 7,
    paddingHorizontal: 9,
    borderRadius: 999,
  },
  resultBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  feedMeta: {
    flex: 1,
    gap: 2,
  },
  opponentText: {
    color: Colors.textDark,
    fontSize: 14,
    fontWeight: '700',
  },
  topicText: {
    color: Colors.darkGray,
    fontSize: 12,
    fontWeight: '500',
  },
  dateText: {
    color: '#999',
    fontSize: 11,
  },
  eloChange: {
    fontSize: 14,
    fontWeight: '800',
  },
  detailPanel: {
    borderRadius: 16,
    backgroundColor: '#FAFBFD',
    borderWidth: 1,
    borderColor: 'rgba(26,26,26,0.04)',
    padding: 12,
    gap: 12,
  },
  detailHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  detailOpponent: {
    color: Colors.textDark,
    fontSize: 16,
    fontWeight: '800',
  },
  detailTopic: {
    color: Colors.darkGray,
    fontSize: 12,
    fontWeight: '500',
    marginTop: 2,
  },
  detailDate: {
    color: '#999',
    fontSize: 11,
    marginTop: 2,
  },
  resultChip: {
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 999,
  },
  winChip: {
    backgroundColor: '#E6F8EE',
  },
  lossChip: {
    backgroundColor: '#FDEBEC',
  },
  resultChipText: {
    color: Colors.textDark,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  questionList: {
    gap: 10,
  },
  questionCard: {
    backgroundColor: Colors.white,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(26,26,26,0.04)',
    gap: 9,
  },
  questionTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  questionStatus: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  correctStatus: {
    backgroundColor: '#1F9D55',
  },
  wrongStatus: {
    backgroundColor: '#D64545',
  },
  questionIndex: {
    color: Colors.darkGray,
    fontSize: 11,
    fontWeight: '600',
  },
  questionPrompt: {
    color: Colors.textDark,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  answerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  answerLabel: {
    color: Colors.darkGray,
    fontSize: 11,
    fontWeight: '600',
    flex: 1,
  },
  answerValue: {
    color: Colors.textDark,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'right',
    flex: 1,
  },
  explanationBox: {
    backgroundColor: '#FFF5F5',
    borderRadius: 12,
    padding: 10,
    gap: 4,
  },
  correctBox: {
    backgroundColor: '#F3FBF6',
  },
  explanationTitle: {
    color: Colors.textDark,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  explanationText: {
    color: Colors.darkGray,
    fontSize: 12,
    lineHeight: 17,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    maxHeight: '90%',
  },
  reviewPanel: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 32,
    gap: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  modalTitle: {
    color: Colors.textDark,
    fontSize: 18,
    fontWeight: '800',
  },
});
export default styles;